INSERT INTO USER (ID, CREATE_AT, MODIFIED_AT, LAST_LOGIN_AT, EMAIL, IS_ACTIVE, NAME, PASSWORD)
VALUES (1001, SYSDATE(), SYSDATE(), SYSDATE(),'jsati@prb.cl', TRUE, 'sati', '$2a$10$U9d86pBNApiB4hQ5YBTN0uq59hdy7I5Ihx6uDplXDm6Xofmjh.FOK');

